### ISSUE TITLE
`__typename` not properly disambiguating the union when it's included in a fragment

### ISSUE THREAD

**Issue by aradalvand** [0no-co/gql.tada#100]
### Describe the bug

The following screenshot is hopefully descriptive enough:

![image](https://github.com/0no-co/gql.tada/assets/26527405/7c945825-1494-4f75-b979-1b7ef771f8ce)

Repro:
- `git clone https://github.com/aradalvand/sveltekit-gqltada-test`
- `pnpm install`
- Go to the `src/lib/index.ts` file
- Notice the error on the second last LOC.
- Now move the `__typename` from the `lessonTitleCard` fragment and include it directly in `lessonForLearningPage`
- Notice that now things work.

### Reproduction

https://github.com/aradalvand/sveltekit-gqltada-test

### gql.tada version

1.2.1

### Validations

- [X] I can confirm that this is a bug report, and not a feature request, RFC, question, or discussion, for which [GitHub Discussions](https://github.com/0no-co/gql.tada/discussions) should be used
- [X] Read the [docs](https://gql-tada.0no.co/).
- [X] Follow our [Code of Conduct](https://github.com/0no-co/gql.tada/blob/main/CODE_OF_CONDUCT.md)

**Comment by kitten** [comment]
I was about to leave a longer explanation, but, basically, it's hard and long to explain what's going on here and why it's not “just” possible to merge these types and help the type checker out.

Generally, what I will say is that `gql.tada` basically creates a selection type for each possible type of an abstract type, i.e. each type in a union creates a separate selection, and for interfaces for each type that implements the interface it creates a separate selection.

The problem here is two-fold.
A genuine bug was that we failed to keep the type narrow when the fragment is in the same document. This is easily preventable and was unexpected. That's an easy fix and prevents mistakes, as shown above. In your example repo you can see this bug by moving the `lessonTitleCard` fragment directly below and into the fragment document below it.
That's fixeable though.

However, debatably, the case you have here is more complex as it can only occur with unmasked fragments and when not selecting the `__typename` field consistently. Our behaviour here prevents mistakes but looks a little odd as what happens is that TypeScript correctly says that _every_ possible type _may_ occur with any possible selection. That's because it has no properties to merge on that consistently appear in both fragments.

I did find a way to get around this though without making type inference complexer. We can add `__typename` as an optional field to these selections. Optional so that it's clear it's not been requested (which also becomes required when the field _is_ requested in any selection), and so that TypeScript has a consistent property to merge on again, since we treat `__typename` in a special way.
