### ISSUE TITLE
RFC: Allow to use the automatic types without fragment refs/masks

### ISSUE THREAD

**Issue by chamatt** [0no-co/gql.tada#23]
## Summary

Currently fragment masking is enabled by default and there's no way to disable it.

## Proposed Solution

Fragment masking introduces a lot of overhead for people that are not used to dealing with it, and could be a blocker for introducing the library into the codebase.

## Requirements

Allow to disable fragment masking, that way, a query is fully typed and fragments are unwrapped.

**Comment by JoviDeCroock** [comment]
From my point of view, we are trying to encourage good patterns so I'm not sure we want to disable the fragment-masking as this pushes folks into co-locating their data-requirements with the blueprints to render said data. In establishing these patterns GraphQL clients can also more reliably make optimisations in terms of rendering bailouts or hooking into technologies like `Suspense` to enable partial UI with `@defer`.

**Comment by chamatt** [comment]
Thanks for the response. Also find the patterns around fragment masking pretty interesting, sadly other folks in the team might not be too willing to make this drastic change in the way they approach graphql, especially since we're using apollo, which doesn't incentivise using this pattern.
I'll try this out some more, as it's the only typed graphGL library that worked well with our codebase (graphqlcodegen client-preset is simply too slow, TS server slows a crawl :/)

Great work you've done here!

**Comment by Hebilicious** [comment]
An interesting solution that [Houdini](https://houdinigraphql.com/api/fragment#fragment-masking) uses is to introduce some special client only directives, such as @mask_disable

```gql
query CurrentUser {
	me {
		uuid
		...UserProfile @mask_disable
		...UserMeta
	}
}
```
This would disable the masking for this field only.

**Comment by chamatt** [comment]
> An interesting solution that [Houdini](https://houdinigraphql.com/api/fragment#fragment-masking) uses is to introduce some special client only directives, such as @mask_disable
> 
> ```graphql
> query CurrentUser {
> 	me {
> 		uuid
> 		...UserProfile @mask_disable
> 		...UserMeta
> 	}
> }
> ```
> 
> This would disable the masking for this field only.

Love this! would be great as an opt-in approach!

**Comment by kitten** [comment]
@Hebilicious: Awesome to see! I had a similar idea to disable fragment masking for `gql.tada`, so that does validate my hypothesis that it should be supported with a directive 💯

In essense, it's not that hard for us to implement.
Fragment types are already inferred and we'd basically want to map to `ResultOf<typeof fragment>` rather than `makeFragmentRef<typeof fragment>`. So, it's all possible in theory, but I'll have to validate that.

One problem may be that this may cause some type checking performance issues, if the level of fragments is sufficiently deep. But again, something to test.

In general, the directive would likely have to look different though, since we'd have to filter it out during runtime. In `@urql/core` we do support filtering out directives starting with underscores `_` as local.
However, we can't rely on that, since this tool supports more than just `urql`. So, we'd have to add additional filtering.
I'm not a big fan of introducing this as an added step. However, my prior assumption was that it's potentially also an option to mark fragment definitions as unmasked instead, which makes filtering the directive out very cheap.
