### ISSUE TITLE
`generate` throw `Cannot query field 'isOneOf'`

### ISSUE THREAD

**Issue by Hashs7** [0no-co/gql.tada#316]
### Describe the bug

When I'm running the command `gql.tada generate output` using version above  1.7.0, I encounter an error: `Cannot query field 'isOneOf' on type '__Type'`. 

### Behavior
The command should generate the file `graphql-env.d.ts` but it throw the error without creating the file.
It seems like `gql.tada` is trying to query a field that doesn't exist in our schema.
Our GraphQL API endpoint `https://api.oees-kraken.energy/v1/graphql/` doesn't expose the `isOneOf` field on the `__Type`.
[This suspected PR](https://github.com/0no-co/gql.tada/pull/284) might have introduce this bug.

There is an possible solution to ensure that the field exists before trying to query it ?

### Reproduction

```ssh
npx gql.tada generate schema 'https://api.oees-kraken.energy/v1/graphql/'
```

### gql.tada version

gql.tada >= v1.7.0

### Validations

- [X] I can confirm that this is a bug report, and not a feature request, RFC, question, or discussion, for which [GitHub Discussions](https://github.com/0no-co/gql.tada/discussions) should be used
- [X] Read the [docs](https://gql-tada.0no.co/).
- [X] Follow our [Code of Conduct](https://github.com/0no-co/gql.tada/blob/main/CODE_OF_CONDUCT.md)

**Comment by JoviDeCroock** [comment]
That would mean that when we run the `supportQuery` that the introspection of the introspection tells us we can use that property 😅 When we execute [this query](https://github.com/0no-co/gql.tada/blob/main/packages/internal/src/loaders/introspection.ts#L85) we derive whether you support `isOneOf` on `__Type`. When we see the property is present we'll add it to the introspection like [this](https://github.com/0no-co/gql.tada/blob/main/packages/internal/src/loaders/introspection.ts#L346-L348).

Would you mind running the support query on your endpoint and seeing what it comes up with? Mind also check the definition of `__Type`?

**Comment by kitten** [comment]
We could probably make this more obvious in the CLI, but the issue here is that the support query [fails with authorization errors](https://api.oees-kraken.energy/v1/graphql/#query=query%20IntrospectSupportQuery%20%7B%0A%20%20directive%3A%20__type(name%3A%20%22__Directive%22)%20%7B%0A%20%20%20%20fields%20%7B%0A%20%20%20%20%20%20name%0A%20%20%20%20%20%20args%20%7B%0A%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20field%3A%20__type(name%3A%20%22__Field%22)%20%7B%0A%20%20%20%20fields%20%7B%0A%20%20%20%20%20%20name%0A%20%20%20%20%20%20args%20%7B%0A%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20type%3A%20__type(name%3A%20%22__Type%22)%20%7B%0A%20%20%20%20fields%20%7B%0A%20%20%20%20%20%20name%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20inputValue%3A%20__type(name%3A%20%22__InputValue%22)%20%7B%0A%20%20%20%20fields%20%7B%0A%20%20%20%20%20%20name%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D&operationName=IntrospectSupportQuery) (see link)

The problem is pretty common with GraphQL APIs that, over HTTP, require someone to authenticate before sending requests, but that's why we often recommend to use a source SDL file instead.

In this case, the API seems to guard against `__type` selections, but does allow `__schema`, which is unusual and feels unintentional

**Comment by kitten** [comment]
I've submitted a fix, since I think we can have better fallback behaviour here
