### ISSUE TITLE
RFC: Deno support 

### ISSUE THREAD

**Issue by Kotletka89** [0no-co/gql.tada#343]

**Comment by kitten** [comment]
I'd appreciate if at least the initial parts of the RFC template are filled out here. It's hard to gauge demand of this, I'll just say this beforehand. We've released some libraries on JSR and this hasn't been the smoothest process.
I'd suspect that our sub-dependencies (especially for Svelte/Vue support) will be a temporary blocker here, and importing TypeScript itself will also be a problem unless we reach for `npm:*` import specifiers. Overall, I'm not really inclined to do the amount of research needed, without seeing the right signals in interest and demand. Sorry

As per what is in the RFC template, there's sections there that really shouldn't be ignored as they give us a lot of initial information and require a baseline of some of the above research questions to be answered:
> Describe in a couple of words *what* you're proposing.
> If relevant, include *why* this should be addressed now.
> The problem should be clearly stated and the solution should be summarised.
> *How* will this change be implemented, and how does it work?

These templates are there for a reason. Please don't ignore them ❤️ 
I'll close this for now, since I don't think we have the bandwidth to do all the prerequisite work and research, while also not knowing the demand for this

**Comment by JoviDeCroock** [comment]
For clarity, everything `gql.tada` specific should work, the only thing that isn't implemented in Deno is the TypeScript Language Server plugin which isn't really on our side to start supporting. Last time I tried I had no issues running the CLI to get an introspection and using `graphql()` to get types from my written GraphQL documents. If that has changed by now, we'd need to know what issues you are running into rather than just throwing an empty issue at us (which is really disrespectful).

If the only thing you are missing is the LSP plugins then this issue is better suited for the deno repository.
