### ISSUE TITLE
gql.tada doctor - unable to use the command for monorepos

### ISSUE THREAD

**Issue by Shishouille** [0no-co/gql.tada#357]
### Describe the bug

Hi guys! First I wanted to say a big thanks for this library, it's a great tool 😃 
So, we currently are in a monorepo config with a tree looking like this:
```bash
├── apps
│   ├── app1 // Where tsconfig + gql.tada is
│   └── app2 // Where tsconfig + gql.tada is
├── package.json // Where Typescript is installed
└── pnpm-workspace.yaml
```

And when lunching the script, I got this error:
<img width="502" alt="image" src="https://github.com/user-attachments/assets/bc7d230a-9f13-409a-9267-158340f1b46f">

Is it ok to either: 

- add a command like --tsconfig to add the location of typescript
- automatically use the client's global typescript if no typescript found
- find a way to check if it's a monorepo (maybe with .git) and look at higher levels

Thank you 🙏 

### gql.tada version

gql.tada 1.8.3

### Validations

- [X] I can confirm that this is a bug report, and not a feature request, RFC, question, or discussion, for which [GitHub Discussions](https://github.com/0no-co/gql.tada/discussions) should be used
- [X] Read the [docs](https://gql-tada.0no.co/).
- [X] Follow our [Code of Conduct](https://github.com/0no-co/gql.tada/blob/main/CODE_OF_CONDUCT.md)

**Comment by kitten** [comment]
This seems to be more of a question rather than an issue, so I don't think we'll need to make changes for this.

First of all, I'm curious whether you're using project references. We're currently looking for examples of how people use composite projects, so please let me know if that applies to you.

There's several points here that are relevant:
- You should still install and set up `typescript` where you're installing and using `gql.tada`. The same kind of applies to other things to like `tsc`. This is especially important with `tsc`, for example, so it applies for other reasons. You can see in the `gql.tada` repo itself, for example, how TypeScript is installed on every package individually (but tied together with a `pnpm.overrides.typescript` entry in the root, just to be sure)
- It's still fine to ignore this, and the peer dependency on `typescript` in `gql.tada` should still have been resolved by it. We can probably make the warning less aggressive, but just noting that `doctor` detects setup issues, but that doesn't mean it's guaranteed to work no matter whether it found issues or not
- If you run commands like `check` you can indeed point it at a specific `--tsconfig` to alter where it starts searching the target directory from. There are some caveats here, but that's generally the idea.

**Comment by Shishouille** [comment]
Oh, sorry for the bother then @kitten 😀  Thank you for your detailed answer and your amazing job! Actually I need some insight for another topic, I'll write it to the discussions right after this message.
So yes, we're also using project references (if you're talking about `"workspace:*"` imports), but the usage of gql.tada is isolated in each project.
