### ISSUE TITLE
RFC: Add helper function to create Fragment data 

### ISSUE THREAD

**Issue by xuanduc987** [0no-co/gql.tada#38]
## Summary

In component test or storybook, we usually want to pass arbitrary props to the components. But because the fragment type is opaque, the props must unsafe casted to any

## Proposed Solution

Add a helper function, reverse of `readFragment`, to type-safe create mock data.

**Comment by kitten** [comment]
Hm, there's a slight trade-off to be made here, since we can't retroactively unmask all fragments that a particular query uses, so — if anything — I'd say we'd indeed want either a function or a type, e.g. with the name `unsafe_maskResult` that casts the result.

However, I'll have to think about this a little more. Because, all in all, that isn't really much different than doing `as any as ResultOf<typeof query>`, in other words, we can't feasibly validate this, obviously, since we don't know that the data belongs to the query.
So, if anything, it'd just be a “sanctioned” way of casting the data, but inherently unsafe of course 🤔

**Comment by kitten** [comment]
This is now supported in [`v1.2.0`](https://github.com/0no-co/gql.tada/releases/tag/gql.tada%401.2.0) via #43.

You can find documentation for this on the API reference docs page:
- [`maskFragments()`](https://gql-tada.0no.co/reference/gql-tada-api/#maskfragments)
- [`unsafe_readResult()`](https://gql-tada.0no.co/reference/gql-tada-api/#unsafe_readresult)
