### ISSUE TITLE
RFC: Support TypedDocumentString

### ISSUE THREAD

**Issue by pauldraper** [0no-co/gql.tada#422]
## Summary

This project causes the graphql parser to be included, which increases client bundle sizes significantly.

Parsing the query at runtime is only necessary for certain GraphQL clients (usually for normalized caching).

## Proposed Solution

Support TypedDocumentString. This is a mode supported by graphql-codegen (https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#documentmode).

This does not parse the input into the GraphQL AST, but instead uses the input string as is.

This could be an option to `initGraphQLTada`, or a different but similar function.

**Comment by kitten** [comment]
`gql.tada` actually doesn't include the GraphQL.js parser, and instead imports `parse` from `@0no-co/graphql.web`, a spec-compliant implementation of parts of GraphQL.js that are commonly used by GraphQL clients: https://github.com/0no-co/graphql.web
This also either matches or beats GraphQL.js on performance on all its included utilities/exports. More info can be found in its readme.

If you're using a GraphQL client that doesn't use this library (e.g. Apollo) you may also use [`graphql-web-lite`](https://github.com/0no-co/graphql-web-lite), which reduces the bundlesize impact of common GraphQL.js utilities by using `@0no-co/graphql.web` and replacing other common utilities.

We haven't supported `TypedDocumentString` for three main reasons:
- all GraphQL clients except simple fetch wrappers eventually rely on the AST and hence need documents to be parsed. If not, this often negates a lot of using GraphQL
- providing a separate utility to output `TypedDocumentString` requires us to split the entire API in two, which — while possible — is just too much API surface to duplicate for little benefit
- as stated above, `@0no-co/graphql.web` negates a lot of the usual bundlesize concerns and is compact enough for us not having to worry about this impact, since other libraries easily outweigh it
