### ISSUE TITLE
'generated/graphql-env.d.ts' not included in /dist output

### ISSUE THREAD

**Issue by mr-zwets** [0no-co/gql.tada#424]
### Describe the bug

Hello 😄 

I'm exporting a typed `graphql` function from my library with custom scalars, but I noticed an issue with the typescript build output with `gql.tada@1.8.10`.

My `dist/graphql.d.ts` is importing `introspection` but the type file is not included in the typescript build output...

```ts
import { initGraphQLTada } from 'gql.tada';
import type { introspection } from './generated/graphql-env.d.ts';
export declare const graphql: initGraphQLTada<{
    introspection: introspection;
    scalars: {
        _text: string;
        bigint: string;
        bytea: string;
        enum_nonfungible_token_capability: "none" | "mutable" | "minting";
        timestamp: string;
    };
}>;
```

Verified that this issue is solved by downgrading to/pinning `gql.tada@1.8.2`

I made this commit to my repo (https://github.com/mr-zwets/chaingraph-ts) so the /dist ouput before and after can easily be compared.

### Reproduction

https://github.com/mr-zwets/chaingraph-ts

### gql.tada version

gql.tada@1.8.10

### Validations

- [X] I can confirm that this is a bug report, and not a feature request, RFC, question, or discussion, for which [GitHub Discussions](https://github.com/0no-co/gql.tada/discussions) should be used
- [X] Read the [docs](https://gql-tada.0no.co/).
- [X] Follow our [Code of Conduct](https://github.com/0no-co/gql.tada/blob/main/CODE_OF_CONDUCT.md)

**Comment by kitten** [comment]
While I understand that this is confusing, this is expected behaviour, or rather an "expected breaking case",

The corresponding fix was introduced in #377 for #376. If you read the report in #376, you'll see why we needed to break the inference chain. if you build with the older version, you can see that the _entire_ introspection type is re-inferred then copied to _your_ output typings by TypeScript. This is not only inefficient from an inference standpoint (i.e. slows the `tsc` output process down) but also (because it's inefficient) TypeScript introduced a limit on how much it can output during this inference process.

This is why we explicitly broke this inference chain to make this issue impossible.

Basically, there's two sides to look at this issue:
- Exporting a gql.tada `graphql` function is not expected usage (partly, since the plugin wouldn't carry over to any importer, and only the "other" exports you provide in your library are expected)
- Since the introspection typings file is generated, and typings are separately generated by `tsc`, it's not expected that the `.d.ts` file is copied, since TypeScript doesn't technically process typings file, so it only worked because of the inference chain before

So, if you want this to still work, you need to copy the `d.ts` file to your output typings folder manually during your `tsc` output process, or re-introduce the inference chain inline (but the former is preferred), or not provide an arbitrary `graphql` function export in the first place.

The reason why the latter is recommended (i.e. not exporting an arbitrary `graphql` function with `gql.tada` for "userland" of your library) is that your library's users would otherwise have to know that they should use the TypeScript plugin, would still need to configure the plugin with the corresponding schema, and would need to know about the additional CLI tools for other features (e.g. turbo mode)

**Comment by mr-zwets** [comment]
Thanks for the response 🙏 

Alright so I see, I'll modify my build script to copy the `d.ts` file to work around this 👍 

Exporting `graphql` is essential for my library because I'd like to abstract all the setup needed to get urql & typings set-up, standardize the common usecases but still provide the possibility of writing arbitrary queries/subscriptions...

> or not provide an arbitrary graphql function export in the first place.
>
>The reason why the latter is recommended (i.e. not exporting an arbitrary graphql function with gql.tada for "userland" of your library) is that your library's users would otherwise have to know that they should use the TypeScript plugin, would still need to configure the plugin with the corresponding schema, and would need to know about the additional CLI tools for other features (e.g. turbo mode)

I'm not sure what any of this means, I don't even think I am using any typescript plugin/plugin schema in VS code 🤔 
I'm a user of the library myself and had to do zero config when installing it, so could you elaborate?

**Comment by kitten** [comment]
I'm referring to setting up the plugin here: https://gql-tada.0no.co/get-started/installation#step-2-%E2%80%94-configuring-a-schema
so that's the part that'll integrate with TypeScript and give you more diagnostics output in your editor. If that's not in the `tsconfig.json` then you won't get any GraphQL-specific diagnostics — which may or may not be fine for your use-case. I suppose for an escape hatch that seems just fine though

**Comment by mr-zwets** [comment]
thanks! I see now 😄
